name: Build LaTeX PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
        
    - name: Install Japanese fonts
      run: |
        apt-get update
        apt-get install -y fonts-noto-cjk
    
    - name: Verify TeX Live installation
      run: |
        xelatex --version
        fc-list | grep -i noto || echo "Noto fonts may not be installed"

    - name: Compile LaTeX document
      run: |
        xelatex -interaction=nonstopmode tablet_planner.tex
        xelatex -interaction=nonstopmode tablet_planner.tex
    
    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: tablet-planner-pdf
        path: tablet_planner.pdf
        retention-days: 30
    
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: tablet_planner.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
